project_id = "tltfnzgwovgxmnqthwkq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[fetch.resources]]
name = "ffmpeg"
paths = ["@ffmpeg/core", "@ffmpeg/ffmpeg", "@ffmpeg/util"]